coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: master
        flags: null
        paths: null